// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx_zBnpQXMSGAXRqbon3jMRi4rT2oV-Sw',
    appId: '1:432943315119:web:de1a121c3e5e2d4aaefc5a',
    messagingSenderId: '432943315119',
    projectId: 'elevate-ecommerce-82e30',
    authDomain: 'elevate-ecommerce-82e30.firebaseapp.com',
    storageBucket: 'elevate-ecommerce-82e30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQjACl55zBP7Zq-Y25-83uLI--frstWzQ',
    appId: '1:432943315119:android:59888fa50b754042aefc5a',
    messagingSenderId: '432943315119',
    projectId: 'elevate-ecommerce-82e30',
    storageBucket: 'elevate-ecommerce-82e30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7AerA4S5Pff-_j4AIdxjSMKiHNtxdQYE',
    appId: '1:432943315119:ios:4210f7466845d09daefc5a',
    messagingSenderId: '432943315119',
    projectId: 'elevate-ecommerce-82e30',
    storageBucket: 'elevate-ecommerce-82e30.appspot.com',
    iosClientId: '432943315119-62dr7hc724cj1c2kgqd2ri56d7mnblhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.elevateEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7AerA4S5Pff-_j4AIdxjSMKiHNtxdQYE',
    appId: '1:432943315119:ios:4210f7466845d09daefc5a',
    messagingSenderId: '432943315119',
    projectId: 'elevate-ecommerce-82e30',
    storageBucket: 'elevate-ecommerce-82e30.appspot.com',
    iosClientId: '432943315119-62dr7hc724cj1c2kgqd2ri56d7mnblhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.elevateEcommerce',
  );
}
